### ISSUE TITLE
Brainstorm Problem Statement Artifact

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#101]
Just as important as generating problem statements is ensuring they can be of use, both to the digital services team & to the wider branch.

Acceptance Criteria:
- [x] Generate objectives for problem statement artifact
- [x] Brainstorm potential ways to capture problem statements
- [x] Compile problem statements from each program area
- [x] Create rough version of artifact
- [x] Pass to project team & PR for feedback
- [x] Iterate on feedback, if needed
- [x] Build out artifact

**Comment by pbastia** [comment]
Thanks for the hard work @jaimiebutton !
