### ISSUE TITLE
Strategize for Mapping Sessions

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#103]

**Comment by hannavovk** [comment]
@jaimiebutton Is this referring to process mapping sessions with IRC? If so we can probably either edit this ticket to add the info for the Registration mapping session that we will likely plan for July 12. Or we close this one and make a new ticket for that?

**Comment by jaimiebutton** [comment]
hey @hannavovk , this is a pretty old ticket (from March) refererring to previous mapping sessions. Happy to close this ticket and make a new one for the Registration session once we know the scope for that.
