### ISSUE TITLE
Metabase Interview w/Cam

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#108]
Let's meet with some identified folks for conversations on how well Metabase is suiting their needs.

Acceptance Criteria:
- [x] Meet with Cam
- [x] Document conversation in Teams doc
- [x] Document action items, if any

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton . I'm so excited to see the outcome of all the discovery and feedback from users!
