### ISSUE TITLE
Complete rough 'Overview' section

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#111]
Let's start working on our internal research plan!

Acceptance Criteria:
- [x] Write project description
- [x] Write research phases
- [x] Write team composition & roles
- [x] Review with @jaimiebutton

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton, please complete the description and acceptance criteria before sprint planning tomorrow :)

**Comment by nanyangpro** [comment]
Hi @jaimiebutton - This part is completed and ready for you to review. I'll continue to #112 as discussed while waiting for your comments/suggestions! Thank you!

**Comment by jaimiebutton** [comment]
Thank you so much Nan for your work on this! I've left a comment about adding to the 'phases' section when we're unblocked from the MVP mapping work.

**Comment by nanyangpro** [comment]
Hi @pbastia - This ticket is ready for your to review and can be closed with the following sections planned, documented, and reviewed by @jaimiebutton in [Miro](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764553828807026&cot=10):

- 1.1 About this research plan
- 1.2 Research phases
- 1.3 Team composition

**Comment by pbastia** [comment]
Excellent work! Thank you @nanyangpro  and @jaimiebutton !
