### ISSUE TITLE
Complete rough 'Goals & questions' section

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#112]
Let's start working on our internal research plan!

Acceptance Criteria:
- [x] Write hypothesis/key problem statement
- [x] Write goals for research
- [x] Write business objectives tied to goals
- [x] Write key outputs/outcomes
- [x] Review with @jaimiebutton

**Comment by nanyangpro** [comment]
Hi @jaimiebutton - [This part](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764551921872810&cot=14) is completed and ready for you to review. I've started #113 and will continue tomorrow. Thank you for your ongoing input and suggestions!

**Comment by nanyangpro** [comment]
Hi @pbastia - This ticket is ready for your to review and can be closed with the following sections planned, documented, and reviewed by @jaimiebutton in [Miro](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764553828807210&cot=10):

- 2.1 Research hypothesis
- 2.2 Research objectives
- 2.3 Ouputs & outcomes

**Comment by pbastia** [comment]
Amazing. Thank you @nanyangpro and @jaimiebutton !
