### ISSUE TITLE
Complete rough 'Logistics' section

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#113]
Let's start working on our internal research plan!

Acceptance Criteria:
- [x] Document participant groups identified & ideal number of participants
- [x] Ideate research methods
- [x] Detail where research will be documented
- [x] Review with @jaimiebutton

**Comment by nanyangpro** [comment]
Hi @pbastia - This ticket is ready for your to review and can be closed with the following sections planned, documented, and reviewed by Jaimie in [Miro](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764553828807233&cot=10):

- 3.1 Methods
- 3.2 Participants
- 3.3 Outreach Plan
