### ISSUE TITLE
Complete rough 'Analysis & Presentation' section

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#114]
Let's start working on our internal research plan!

Acceptance Criteria:
- [x] Ideate method for analyzing research
- [x] Document how research will be communicated up to execs
- [x] Brainstorm success metrics / Key Performance Indicators
- [x] Review with @jaimiebutton

**Comment by nanyangpro** [comment]
Hi @jaimiebutton - [This part](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764553600674651&cot=14) is completed and ready for you to review. Thank you for your ongoing input and suggestions!

**Comment by nanyangpro** [comment]
Hi @pbastia - This ticket is ready for your to review and can be closed with the following sections planned, documented, and reviewed by @jaimiebutton in [Miro](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764553828807277&cot=10):

- 4.1 Finding analysis
- 4.2 Learning communication

**Comment by pbastia** [comment]
I can see the frames in Miro. Thank you @nanyangpro !
