### ISSUE TITLE
Create external user proto-journey map

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#116]
Let's create a basic map to understand the experience of external users reporting their emissions!

Acceptance criteria:
 - [x] Take stock of past maps that could be helpful for this
 - [x] List out key phases
 - [x] Create draft map
 - [x] Pass map to project team for feedback
 - [x] Iterate on feedback, if needed
 
Goal of this ticket:
- Capture our (very rough) understanding of the operator reporting experience
- Have an artifact we can iterate as we go through discovery & as our understanding changes

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/116?planning-poker) with Zenhub @nanyangpro

**Comment by nanyangpro** [comment]
Thanks @jaimiebutton, Done! Would you think this belong to the Clean Growth Discovery instead (since it's actually part of Phase 1 in the [Internal Discovery Plan](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764551921809995&cot=14))?

**Comment by hannavovk** [comment]
@jaimiebutton I left a comment on one of the items in the proto-journey. Let me know if you agree/disagree and we can close the ticket.

**Comment by jaimiebutton** [comment]
Thanks @hannavovk !
