### ISSUE TITLE
Identify things that are immediately doable

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#118]
This ticket follows #117 where we'll map out our hypothesis MVP.

Acceptance Criteria:
- [x] Of MVP elements mapped out, identify which could be worked on immediately
- [x] Consolidate and prioritize potential topics
- [x] Document any unknowns

Goal of this ticket:
- Be able to create more ZH tickets with upcoming work to be done

_Note: This is a collaborative ticket to be done with the whole team_

**Comment by nanyangpro** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/118?planning-poker) with Zenhub @jaimiebutton
