### ISSUE TITLE
Plan out SWRS review work

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#119]
What will go into this review work? Let's find out.

Acceptance criteria:
- [x] Set up time with Pierre & Team Moose
- [x] Create frame in Miro to guide conversation
- [x] In conversation, identify output of review work
- [x] In conversation, identify who should be involved & informed in this work
- [x] In conversation, identify ideal timeline of documentation/recommendations
- [x] In conversation, plan out work to be done and make tickets accordingly

**Comment by jaimiebutton** [comment]
Conversation scheduled for Tuesday, April 25

**Comment by pbastia** [comment]
Thank you @jaimiebutton ! Conversation happened on April 25
