### ISSUE TITLE
Create structure for external user research plan

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#120]
Our External Discovery plan will help us plan out discovery goals, activities & scope. 

Acceptance Criteria:
- [x] Create space in DST Thinking Miro for external discovery planning
- [x] Create frame for Overview
- [x] Create frame for Goals & Questions
- [x] Create frame for Logistics
- [x] Create frame for Analysis & Presentation
- [x] Bring in research plan from Internal Discovery Plan for context

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/120?planning-poker) with Zenhub @nanyangpro

**Comment by nanyangpro** [comment]
Closed #120 as [completed](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764555378234463&cot=10).
