### ISSUE TITLE
Complete rough 'Overview' section (EXTERNAL PLAN)

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#125]
Let's start working on our external research plan!

Acceptance Criteria:
- [ ] Write project description
- [ ] Write team composition & roles

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/125?planning-poker) with Zenhub @nanyangpro

**Comment by nanyangpro** [comment]
Closed as discussed with the team from the last retro. Will stay away from documenting for the sake of documentation, and instead create executable External Discovery ticket and adjust as we go.
