### ISSUE TITLE
Complete rough 'Logistics' section (EXTERNAL PLAN)

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#127]
Let's start working on our external research plan!

Acceptance Criteria:
- [ ] Document participant groups identified & ideal number of participants
- [ ] Ideate research methods
- [ ] Create draft schedule
- [ ] Detail where research will be documented

**Comment by nanyangpro** [comment]
Closed as discussed with the team from the last retro. Will stay away from documenting for the sake of documentation, and instead create executable External Discovery ticket and adjust as we go.
