### ISSUE TITLE
Estimate cost of SWRS maintenance

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#129]
How much, approximately, does SWRS maintenance cost us every year? Let's find & document that amount.

Acceptance Criteria: 
- [x] Generate rough estimate
- [x] Document estimate in the SWRS Review section of our CPR Miro board
- [x] Share estimate with project team & identified SMEs for review

**Comment by pbastia** [comment]
To get a sense:
- how many pull requests / code
- how many cards and bugs
