### ISSUE TITLE
Coffee Chat w/Emilie

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#13]
Coffee chats are a great way to get to know the people involved in a project, their expectations & improvements they could see.

Acceptance Criteria:
- [x] Reach out to set up coffee chat
- [x] Schedule coffee chat
- [x] Hold coffee chat

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - based on your update at standup. Does this ticket need to be pulled into this sprint?

**Comment by jaimiebutton** [comment]
Pulled in, thanks :)

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton! I'd love to hear your thoughts on next steps and how we can/should support the CPR team.
