### ISSUE TITLE
Brainstorm new 'Product Vision'

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#131]
Acceptance Criteria:
- [x] Schedule time with Team Moose
- [x] Create frame in Miro to facilitate conversation 
- [x] Create Vision Statement template to work with
- [x] As a group, brainstorm the ideal product vision for a new system
- [x] Document brainstorming in SWRS review section of our CPR Miro

Goals of this ticket:
- To be able to best inform documentation, let's capture our collective idea of what a new system would do & the value it would add

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/131?planning-poker) with Zenhub @nanyangpro

**Comment by jaimiebutton** [comment]
Removed Emilie from this ticket as she won't be back before the end of the sprint

**Comment by hannavovk** [comment]
Thanks @jaimiebutton!
