### ISSUE TITLE
Complete 'Risks' section

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#133]
As part of our SWRS documentation for execs, we'll need to communicate the risks of keeping SWRS as well of the risks of developing a new system.

Acceptance Criteria:
- [x] Take stock of risks of keeping SWRS documented in Elliott's report
- [x] List out additional risks of keeping SWRS not in the report
- [x] List out risks of developing a new system
- [x] List out risk mitigation strategies of developing a new system
- [ ] Write this out in paragraph form for the final documentation

**Comment by jaimiebutton** [comment]
Hey @pbastia + @dleard , I've done my pass of the risks section and added strategies for mitigating the risks of developing a new system. Feel free to do a pass too :)

**Comment by pbastia** [comment]
@jaimiebutton @dleard  I've done my pass too, reshuffled some cards. Thank you!
