### ISSUE TITLE
Complete 'Cost Analysis' Section

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#135]
As part of our SWRS documentation for execs, we'll need to communicate the cost analysis of a new system and of keeping the current system.

Acceptance Criteria:
- [x] Roughly calculate the current cost of maintaining SWRS (#129)
- [x] Roughly calculate time spent over the past few years maintaining SWRS
- [x] Roughly calculate the cost of developing a new system
- [x] Write this out in paragraph form for the final documentation

**Comment by pbastia** [comment]
@hannavovk @jaimiebutton @nanyangpro this is ready for review in the document
