### ISSUE TITLE
Complete 'Proposed features of new system' section

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#136]
As part of our SWRS documentation for execs, we'll need to communicate the proposed features of a new system, if we were to build it.

Acceptance Criteria:
- [x] Take stock of new system recommendations from Elliott's report
- [x] List out core functionality of a proposed new system
- [x] List out features that SWRS currently does not have

**Comment by pbastia** [comment]
Document risk of not knowing the requirements for ECCC compliance, this is a big question mark
