### ISSUE TITLE
Check in w/ ICPG (Engagement Team + Patricia + Ali) to understand overlap with our discovery plan

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#138]
How does our internal discovery plan align with the ICPG team's (the engagement team, Ali & Patricia) work to be done? Let's find out.

Acceptance criteria:
- [x] Schedule chat with team moose, Engagement Team, and Patricia
- [x] Write meeting agenda
- [x] Present internal discovery plan to folks on the call
- [x] Take note of any overlap
- [x] Iterate on feedback, if recieved

Goals of this ticket:
- Make sure the rest of the ICPG team knows what we're planning for the next few sprints
- Identify any overlap in our work
- Incorporate the ICPG team into our plans where appropriate

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/138?planning-poker) with Zenhub @nanyangpro

**Comment by pbastia** [comment]
Talk about external engagement plans

**Comment by jaimiebutton** [comment]
Hey @pbastia , this ticket is for our internal plan (as we don't have an external plan yet). Still think it's relevant? cc @nanyangpro

**Comment by pbastia** [comment]
Definitely. Thank you @jaimiebutton !

**Comment by jaimiebutton** [comment]
Awesome! Call scheduled for Tues, May 23.
