### ISSUE TITLE
Coffee Chat w/Alicen

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#14]
Coffee chats are a great way to get to know the people involved in a project, their expectations & improvements they could see.

Acceptance Criteria:
- [x] Reach out to set up coffee chat
- [x] Schedule coffee chat
- [x] Hold coffee chat

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton! Hope it was a delicious coffee :)
