### ISSUE TITLE
Investigate the OBPS Regulatory Engagement Survey results

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-review#141]
#### Describe the task

Alicen sent out the [OBPS Regulatory Engagement Survey](https://submit.digital.gov.bc.ca/app/form/submit?f=c35e4d04-c8c7-4f99-aa6e-d74a535e7ee7) on Day 1 - CleanBC Program for Industry workshop. There were many relevant questions asked and might have overlapping space with our Discovery phase.

#### Acceptance Criteria

- [x] Reach out to Alicen and request survey results
- [x] Get the complete survey results after its due date Tue, May 23rd
- [x] Investigate and compile findings into summarized bullets
- [x] Share compiled findings and learnings with the team

**Comment by nanyangpro** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/141?planning-poker) with Zenhub @jaimiebutton

**Comment by nanyangpro** [comment]
The [first 25 responses](https://bcgov.sharepoint.com/:x:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/CIF/Events,%20Workshops%20%26%20Meetings/CPI%20Workshop%20May%202023/OBPS%20Regulatory%20Survey%20Results.xlsx?d=w9b5ef84fe01f436db91df3dbf3372307&csf=1&web=1&e=kbXd4A) received are compiled and uploaded to our Scrum Team's channel.

**Comment by nanyangpro** [comment]
Hi @pbastia - This ticket is ready for you to review and can be closed.

[OBPS relevant findings](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764556169509599&cot=10) are documented, delivered and discussed with Team Moose with next steps identified that may inform future OBPS external discovery (#125, #126,  #127, #128).

**Comment by hannavovk** [comment]
Great summary @nanyangpro
