### ISSUE TITLE
Check in with Registration team

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#145]
As CT Registration is an upcoming priority, let's meet to with the Registration Task Force™️ to see where they're at.

Acceptance Criteria:
- [x] Schedule time with Team Moose + Task Force members (Robb, Amos, Jairo, Ali)
- [x] Write meeting agenda
- [x] Brainstorm questions for Registration team
- [x] Hold conversation
- [x] Document results

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/145?planning-poker) with Zenhub @nanyangpro

**Comment by pbastia** [comment]
Thanks for arranging this @jaimiebutton !
