### ISSUE TITLE
Consult with key folks about in-person research

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#146]
To make the case for in-person user research, let's compile some key learnings from our network.

Acceptance Criteria:
- [x] Talk to Eric Strauss from CIF to understand what visits they're planning
- [x] Talk to Parks (Jessica/Ashley) to understand process + budget for 4 people
- [x] Ask John N if there are any operators he recommends going to

Outcomes of ticket:
- Get an understanding of when CIF is planning to go out
- Understand the scope/cost of sending a team 
- Identify some operators we could potentially visit

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/146?planning-poker) with Zenhub @nanyangpro

**Comment by nanyangpro** [comment]
Hi @jaimiebutton - Meetings are scheduled with

- Eric S. on Wed, Jun 21
- Jessica W. and Ashley D. on Thu, Jun 22

Feel free to adjust as you see fit. Thanks!

**Comment by nanyangpro** [comment]
[Notes](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764557787372660&cot=14) from the conversations with Eric/Jessica/Ashley.

Hey @jaimiebutton - Thanks for your wonderful questions and notes! Did you see the last AC as a quick check-in with John or preferred emails or direct messages?

**Comment by jaimiebutton** [comment]
Hey @nanyangpro , just reached out to John! I'll add his feedback to the Miro board when I hear back :)

**Comment by nanyangpro** [comment]
Amazing, thanks @jaimiebutton! 

Feel free to move the ticket once done, the rest of it is checked off. :)

**Comment by nanyangpro** [comment]
Hi @pbastia & @hannavovk - This ticket is completed and can be closed once reviewed by you:
- [Notes](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764557787372660&cot=14) from the conversations with Eric/Jessica/Ashley were documented. Thanks @jaimiebutton!
- #151 is unblocked by this effort.

**Comment by hannavovk** [comment]
Thanks @jaimiebutton!
