### ISSUE TITLE
Screenshot screens in CIIP app

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#147]
Let's make sure we have the CIIP work documented! Since we don't have updated wireframes, let's save screenshots of the CIIP app pages in Miro for future quick-looking. 

Acceptance Criteria:
- [x] Ensure we have full access to CIIP screens
- [x] Create a space in Miro to capture this (and note the date of capture in Miro too!)
- [x] Take screenshots of available screens
- [x] Check in with Dylan to see if the are any screens that were missed

Outcomes of ticket:
- Make sure CIIP work is captured for when we start developing OBPS screens
- Have a resource that we can easily check to see screens at a birds-eye-view

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/147?planning-poker) with Zenhub @nanyangpro

**Comment by nanyangpro** [comment]
Hi @pbastia & @hannavovk - This ticket is ready for you to review and can be closed.

- [CIIP app screens](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764557138118083&cot=14) (internal and external) captured for future OBPS design references
- The screens are organized based on user journeys for both Program Administrators and Industrial Operators

**Comment by nanyangpro** [comment]
Thanks for reviewing and great catch, @pbastia! 

- The product and product benchmark screens are captured and added as you suggested.
- As discussed, a [new Miro board](https://miro.com/app/board/uXjVM-Pc1Ag=/?share_link_id=293610057510) is created to host the [CIIP app screens and user workflows](https://miro.com/app/board/uXjVM-Pc1Ag=/?moveToWidget=3458764557228223005&cot=14) for future OBPS design reference.
- This ticket can be closed, unless there's additional input from you or @hannavovk. :)

FYI @jaimiebutton, the size of the screen captures is too big for our DST's CPR Thinking board and was causing loading issues for people, so we decided to keep it in its own space. :)

**Comment by hannavovk** [comment]
Looks great! Thanks @nanyangpro
