### ISSUE TITLE
Coffee Chat w/Hanna

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#15]
Coffee chats are a great way to get to know the people involved in a project, their expectations & improvements they could see.

Acceptance Criteria:
- [x] Reach out to set up coffee chat
- [x] Schedule coffee chat
- [x] Hold coffee chat
- [x] Report back to team if needed

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - based on your update at standup. Does this ticket need to be pulled into this sprint?

**Comment by jaimiebutton** [comment]
Wow I was JUST updating it!

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - I feel this ticket is completed?

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton!
