### ISSUE TITLE
Get a demo of ECCC's Modules and list data fields

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#156]
To know what data we'll be asking for in our system, we first need to know what data is currently being asked for in SWRS. Following #157, let's check out a demo of ECCC's BC GhG Module + Administrative Modules to understand what data it collects.

Jaimie, Dylan, Andrea

Acceptance Criteria:
- [x] Set up time to get demo from QB
- [x] Record demo/take screenshots
- [ ] Upload screenshots of screens to Miro 
- [x] Generate a list of data fields that ECCC collects

Goal/outcome of ticket:
- Understand what data is collected by ECCC
- Have a list we can share with Clean Growth Staff (in a following ticket) to see what data we'll need in the future
- A map of data fields and dependency

**Comment by nanyangpro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/156?planning-poker) with Zenhub @jaimiebutton @dleard

**Comment by andrea-williams** [comment]
Excel spreadsheet: https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/Ed6pxiaFXXdKj15NYLgBBvcBO2k0zLGUtvMo__ncNWV3Uw?e=fe4paY

**Comment by andrea-williams** [comment]
Spreadsheet has been shared with ES & AJ. AJ will be adding in some info for other facility types that I missed.

**Comment by Dianadec** [comment]
Pending IRC review.

**Comment by hannavovk** [comment]
Thanks @andrea-williams for going all that data! It's a tedious job.
