### ISSUE TITLE
Chat with Emilie about SWRS

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#157]
Let's chat with Emilie to unblock our SWRS work.

Acceptance Criteria:
- [x] Set up time (30 mins) to meet with Team Moose + Emilie
- [x] Write goals of session in the meeting invite
- [x] Discuss the SWRS transition
- [x] Ask for a demo of ECCC's BC module

Goal of this ticket:
- Get Emilie's expertise on our SWRS plan
- Get clarification on details we're still unclear about
- Plant the seeds for a BC module demo

**Comment by nanyangpro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/157?planning-poker) with Zenhub @jaimiebutton @dleard

**Comment by pbastia** [comment]
Great discussion! Thanks for organizing @jaimiebutton
