### ISSUE TITLE
Take list of cross-referenced data back to Clean Growth staff

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#158]
Following tickets #156 and #163, let's take the cross-referenced list of datafields from the ECCC demo and Siyue's calculator to Clean Growth staff to ask if there will be any other data they'll need to collect.

Acceptance Criteria:
- [x] Ideate the best format to share with clean growth staff
- [x] Prepare list of datafields in chosen format
- [x] Build in a place for clean growth staff to add additional fields not included in the list
- [ ] Share with key teams (C&E, ICU, R&A, EMU, SI)
- [ ] Ask for review & feedback by a specific date

**Comment by jaimiebutton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/158?planning-poker) with Zenhub @dleard @nanyangpro

**Comment by Dianadec** [comment]
Needs a re-estimate

**Comment by andrea-williams** [comment]
Update: had a meeting with ES's team July 19 to discuss how we'd like them to share their feedback. Haven't set a date for deadline to receive expected feedback, but ES indicated that her team needs to have the data fields fleshed out in their minds before we need it.
