### ISSUE TITLE
Chat with Harnav about compliance workflows + data

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#159]
Dylan mentioned that Harnav has some great ideas for compliance workflows and data that would need to be collected. Let's meet with her to get a better understanding of her vision. 

Jaimie and Dylan 

Acceptance Criteria:
- [x] Set up time with Team Moose + Harnav
- [x] Add goals to meeting agenda
- [x] Create a space in Miro to capture learnings from call
- [x] Chat with Harnav!
- [x] Document what we've learned in the DST's CPR Thinking board

**Comment by jaimiebutton** [comment]
Conversation scheduled for Tuesday, June 13

**Comment by pbastia** [comment]
Conversation was conversed and documented. Thanks @jaimiebutton !
