### ISSUE TITLE
Coordinate w/Jess K

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#16]
Jess K has been tasked with leading engagement. Let's start the conversation around engagement to make sure we're aligned.

Acceptance Criteria:
- [x] Reach out to Jess K
- [x] Schedule coffee chat
- [x] Hold conversation
- [x] Document findings, if applicable

**Comment by jaimiebutton** [comment]
Hey @LindsayMacfarlane, anything to add to this?

**Comment by jaimiebutton** [comment]
Hey @LindsayMacfarlane, how does this ticket fit in with the alignment meeting you were discussing yesterday w/Maral?

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - what's the status of this ticket?

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton ! I look forward to us working more closely with JK and team and seeing how service design & user research ties in together.
