### ISSUE TITLE
Cross-reference data in Siyue's calculator

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#163]
Once we have a list of the data in Siyue's calculator 

Acceptance Criteria:
- [x] Create list of data based on siyue's calculator

Scrum Team > Files > CPR > DRAFT_OBPS calculator for industry_20230613_V2.xlsx
https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/EVqZJtZrtX1Doc-LTLC6ljMB1JCIkxvVuNXkz0otgiMtBQ?e=C71nir&wdOrigin=TEAMS-ELECTRON.p2p.mw&wdExp=TEAMS-CONTROL&wdhostclicktime=1688665268387&web=1

**Comment by jaimiebutton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/163?planning-poker) with Zenhub @nanyangpro @dleard

**Comment by dleard** [comment]
Is this comparison still helpful knowing that only CIIP data was used in the creation of the calculator?

**Comment by jaimiebutton** [comment]
@dleard Maybe not! We can chat about it as I haven't seen the calculator - I defer to you. Our end goal is to have a list of data to pass to clean growth staff, so as long as we capture what we need in there I think we're good :)

**Comment by Dianadec** [comment]
Adjusted the AC so the estimation was lowered.

**Comment by andrea-williams** [comment]
Data fields summarized in this doc:
https://bcgov.sharepoint.com/:x:/t/00608-ScrumTeam/EVefgiiTl7RFnTh5yCc1Um0BKwFRrFVVTg6ICc-8bM-fSQ?e=BRD5lE

**Comment by Dianadec** [comment]
Pending IRC review.

**Comment by hannavovk** [comment]
Thanks @andrea-williams!
