### ISSUE TITLE
Tech Stack Review - Survey & Discussion

### ISSUE THREAD

**Issue by Dianadec** [bcgov/cas-review#165]
#### Describe the task

The goal for this ticket is to run a bit of a retrospective
- async component: maybe a miro board where devs add the different tools, and the advantages or challenges for each, and potentially other tools to explore with the same functionality
- a synchronous retro on this to agree on a path forward

@JoshLarouche you expressed interest in taking a role in this 

#### Acceptance Criteria

- [x] A miro board with the summary
- [x] Create an epic and cards for a deep dive into a stack, and the individiual items in this stack

#### Additional context

* Add any other context about the task here.
* Or here

**Comment by Dianadec** [comment]
Add estimate?

**Comment by pbastia** [comment]
Need to schedule a time to bring the team together
