### ISSUE TITLE
Team Moose: Participatory exploration and design session for OBPS Registration

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-review#166]
#### Describe the task

a 1/2 day workshop where we can chat about what the vision is for the system: not in terms of what we know and don't but how we see the system working.

Idea is to brainstorm system / UI / Data viz / interactions ideas on the reporter workflow
    - Mostly focus on registration
    - Also touch a bit on reporting

Draw low-fidelity prototypes and concepts, that we can use in discussions with stakeholders later, as a "what if we did something like that" tool

#### Acceptance Criteria

- [x] hold a group workshop
- [x] collaboratively ideate:
    - [x] user journeys
    - [x] requirements
    - [ ] lo-fi wireframes
- [ ] ranking and voting for best solutions

**Comment by pbastia** [comment]
Idea: focus on registration and reporting

**Comment by Dianadec** [comment]
Who needs to all be at this session @hannavovk  and @pbastia ? DST + CAS Stakeholders? any SME's?

**Comment by pbastia** [comment]
Yes! A couple of SMEs would be fantastic. With the amount of people we have scheduled we might be able to do 2 groups. In-person could also be an option?

**Comment by hannavovk** [comment]
@Dianadec @pbastia I think the people currently on the invite are good. I'm not sure who we could invite as SMEs. Let's discuss.

**Comment by hannavovk** [comment]
@pbastia RE "Idea: focus on registration and reporting" - my understanding is that the intent here is to brainstorm overall system design/architecture and it shouldn't be focused on any one part of it. 
We should probably get together with team Moose and nail down exactly what our vision is for this session.
cc: @jaimiebutton @Dianadec @nanyangpro [seems like Nicole is not a user yet so I can't CC her]

**Comment by pbastia** [comment]
test

**Comment by nanyangpro** [comment]
Hi @pbastia & @hannavovk - This ticket is completed and can be closed once reviewed by you:
- The Participatory Design Session for **Registration** was held within Team Moose on Wed, Jul 12.
- Deliverables were dropped next to the [planning board](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764558334264717&cot=14). Thanks @Dianadec!
- Next steps:
    - **#176** (repurposed in preparation of #174): compile our questions and requirements for IRC
    - **#174**: mapping session with IRC, currently scheduled on Tue, Jul 18
    - **#187**: create low-fi mock-ups, informed by outcome of this ticket and #174
