### ISSUE TITLE
Create SWRS Document

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#167]
We've done the research, now let's put it all together!

Acceptance Criteria:
- [x] Create a MS Teams document : Saved in Scrum Team > Files > CPR > [powerpoint]
- [x] Write high-level headings in document
- [x] Fill it in with rough bullet points
- [ ] Write complete documentation in paragraph form
- [ ] Pass to rest of team for feedback
- [ ] Iterate on feedback, if needed

**Comment by Dianadec** [comment]
@pbastia I've started this doc using a gov decision note template, and have labelled the miro board with stickies according to the sections. Could we have a quick chat sometime this week to go over some of the wording such as the context?

**Comment by Dianadec** [comment]
I am unclear about the AC point that says to write it in paragraph form. I have put together the powerpoint for the team + Po's review. Still needs some refining but would like your feedback before I continue. Thanks! @pbastia @jaimiebutton

**Comment by hannavovk** [comment]
The deliverable evolved to be a powerpoint, which is now done - thanks @Dianadec! Meeting has been scheduled to share with ED.
