### ISSUE TITLE
Hypothetical user stories & dependencies

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-review#169]
#### Describe the task

We previously mapped out [functionalities needed on the Epic level for the hypothetical MVP](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764553024341952&cot=14). This ticket is to further identify Features required for OBPS internal users in the form of **user stories**, based on our accumulated learnings so far:

> As a **{user role}**, I want to **{user task}**, so that **{user goal, i.e. value to the user}**.

With rough dependencies identified, these user stories would then be used for validation with Clean Growth staff and help inform future design and development.

Upon completion of this ticket, we should have better ideas towards the questions below for each higher priority Epic.

-    What will users use the digital system for? (User Goals)
-    What will users need to do to achieve their goals? (User Tasks)
-    Who will use the digital system to achieve certain goals? (User Roles)

#### Acceptance Criteria

- [x] Chat with Hanna to align understandings and get clarifications
- [x] Identify user goals & user tasks for internal users based on shared understandings/assumptions and accumulated learnings so far
- [x] Define user roles for internal users
- [x] Draft user stories
- [x] Identify dependencies
- [x] Share for internal feedback
- [x] Refine user stories based on feedback

#### Outcomes
- Rough user stories and dependencies

**Comment by nanyangpro** [comment]
Hi @hannavovk & @pbastia - This ticket is created as discussed with you, please feel free to review and refine. Unless there are concerns, I'll move it to the Next Sprint Backlog. Thanks!

**Comment by pbastia** [comment]
Hi @nanyangpro, do you intend to define all the epics into user stories with this ticket? We might want to focus on the highest priority epics and define contents as we go instead. Maybe a touch base with @Dianadec @rdromey on how to do this best in an Agile way could be helpful

**Comment by nanyangpro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Moose-Sprint-Board-60d216175a2689000ec774d0/issues/bcgov/cas-review/169?planning-poker) with Zenhub @andrea-williams @dleard @jaimiebutton

**Comment by nanyangpro** [comment]
Hi @hannavovk - As discussed, this ticket is completed and can be closed once reviewed by you:
- The scope of the ticket expanded from 
    - **Clean Growth users only** 
to 
    - **Internal (Clean Growth) + External (Industry) users**, 
since their user goals/tasks are depended on each other
- **Deliverables:**
    - [Hypothetical User Stories (Roles + Tasks + Goals)](https://miro.com/app/board/uXjVP1NVDKE=/?moveToWidget=3458764557314037968&cot=14)
    - [Hypothetical Process/Dependency Map for Users](https://miro.com/app/board/uXjVP1NVDKE=/?moveToWidget=3458764557870516575&cot=14)
- To be used to inform UX/UI design going forward, the artifacts above require further refinement/validation from the business area, and should be updated once periodical alignments/agreements are achieved.

**Comment by hannavovk** [comment]
This is a great visual, thanks @nanyangpro! I think for the purposes of this ticket we can consider it done and, as we discussed, the will be further refined through future work.
