### ISSUE TITLE
Hold registration session (IRC + DST Mapping Session)

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#174]
Co-design with Team Moose + the registration team

Acceptance Criteria:
- [x] Send out agenda ahead of time
- [x] Hold session
- [x] Document next steps

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/174?planning-poker) with Zenhub @nanyangpro

**Comment by hannavovk** [comment]
Great work everyone! Thanks for organizing and facilitating @jaimiebutton @Dianadec and Nicole (I can't tag you?!)
