### ISSUE TITLE
Digitize registration process map

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#175]
Let's take the map we created in July 18th's registration mapping session and make sure it's a tool we can use going forward. 

Acceptance Criteria:
- [x] Digitize process map created in IRC registration mapping session 
- [x] Add questions/unknowns
- [x] Pass map to Moose team for feedback
- [ ] Iterate on feedback, if needed
- [x] Pass map to IRC team (and transfer to their own Miro board, if preferred) 

Goal of this ticket: 
- Create a digital artifact we can keep iterating on
- Ensure IRC has a working map they can use

**Comment by jaimiebutton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/175?planning-poker) with Zenhub @nanyangpro @andrea-williams

**Comment by nanyangpro** [comment]
Assigned to @Dianadec as discussed during the stand-up on Wed, Jul 19. Thank you!

**Comment by jaimiebutton** [comment]
Hey team, is this ticket ready to be closed?

**Comment by Dianadec** [comment]
@jaimiebutton  yes I believe so - we also have a follow up meeting with IRC so we can get an update from them then.
