### ISSUE TITLE
Post IRC session alignment

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#176]
From the Participatory Design Session on Wed, Jul 12, the team want to prepare:
- A list of **our questions** pending discussion with IRC
- A list of **requirements** pending validation/refinements with IRC

This ticket is for the team come together to align ourselves internally to form the next steps with IRC post the session with them on Tuesday, Jul 18.

**Update:** As discussed by PO and designers on Thu, Jul 20, this ticket is repurposed. Instead of lists of questions and requirements, we decided to visualize and present our proposal with a diagram tagging questions/requirements for IRC wherever fit. - Nan

**Update:** As discussed during Moose Working Meeting on Fri, Jul 21, Dylan & Andrea will carry forward the next steps including refining their diagram and reach out to designers/PO for input. AC has been updated to include it. - Nan

**Update:** As discussed during Moose Working Meeting on Fri, Jul 28, @dleard & @andrea-williams will add **Workflow 3 for granting carbon tax exemption** to [our proposal to IRC ](https://miro.com/app/board/uXjVM0yeqXQ=/?moveToWidget=3458764560280154235&cot=14)(ideally before next Wednesday afternoon when we touch base with IRC). - Nan (cc: @hannavovk, Nicole)

Acceptance Criteria:
- [x] Moose PO + Design Team meet to align (July 20)
- [x] Schedule time with Team Moose to meet (approx. 1 hr)
- [x] Dylan/Andrea iterate on the [diagram](https://miro.com/app/board/uXjVM0yeqXQ=/?moveToWidget=3458764560280154472&cot=14) with Designer's feedback
- [x] Team Moose internal alignment during Moose Working Meeting, Friday, Jul 28
- [x] Drop our questions for IRC wherever fit on the diagram
- [x] Drop our requirements pending IRC input wherever fit on the diagram
- [x] Nan prettifies the diagram and ask Hanna to deliver to IRC

**Comment by nanyangpro** [comment]
@hannavovk @pbastia @dleard @andrea-williams @jaimiebutton Nicole
As discussed during the Moose Refinement, this ticket is repurposed with details added in the description. Please review/refine as you see fit!

**Comment by hannavovk** [comment]
May also as part of this prep we can make sure we know what IRC's DI says on registration and incorporate that into our hypothesis RE requirements. See [Registration DI](https://bcgov.sharepoint.com/:w:/t/00608-ScrumTeam/Ec7O6BjlDb5MhRFLtRP9wUcByIZkDhYou9sOvUb48YXubg?e=OPYiY2) for reference.

**Comment by nanyangpro** [comment]
As discussed with @hannavovk on Fri, Jul 14, removing the "Backlog Refinement" label.

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/176?planning-poker) with Zenhub @nanyangpro

**Comment by nanyangpro** [comment]
Hi @hannavovk & @patriciarussellCAS - This ticket is ready for you to review and can be closed with:
- proposed Registration [workflows](https://miro.com/app/board/uXjVM0yeqXQ=/?moveToWidget=3458764560280154235&cot=14) and [screens](https://miro.com/app/board/uXjVM0yeqXQ=/?moveToWidget=3458764560280154236&cot=14) (thanks @andrea-williams & @dleard!) with our questions/requirements refined and delivered to IRC (thanks @hannavovk!)
- a walkthrough session of above proposals scheduled with IRC on Thu, Aug 10 as requested.

**Comment by hannavovk** [comment]
Great work @nanyangpro
