### ISSUE TITLE
Timeline for External User Research

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#178]
What our timeline for external user research?

Acceptance Criteria:
- [x] Identify first few research topics (eg. Registration, Emissions Reporting, etc.)
- [x] Identify how long we would need to prepare for external research
- [x] Create rough timeline to show when we would like to start external user research
- [x] Pass to Team Moose for feedback

Goal of ticket: 
- Know what's coming next!
- Let policy team know when we're planning to speak to external stakeholders

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/178?planning-poker) with Zenhub @nanyangpro

**Comment by hannavovk** [comment]
Thanks @jaimiebutton!
