### ISSUE TITLE
Identify Topics for External User Research

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#179]
What topics do we want to consult with external users on?

Acceptance Criteria:
- [x] Brainstorm OBPS digital system 'pieces' that will we will need external feedback for (eg. registration, emissions reporting) 
- [x] Pass brainstormed list to Team Moose
- [x] Pass brainstormed list to ICPG team 

Goal of ticket:
- Get a better understanding of what we'll need to consult with industry on 
- Have topics to share with the Policy team to see where there's overlap in our research

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/179?planning-poker) with Zenhub @nanyangpro

**Comment by hannavovk** [comment]
@jaimiebutton, can you confirm where I can find the deliverable to review? Assuming this is the "[Topics for external user discovery](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764558008244996&cot=14)" frame in DST's CPR Thinking? If so then I've reviewed that and can approve and close the ticket (fyi, left one small comment in there).

**Comment by hannavovk** [comment]
Concluded in conjunction with #178 that it was the right spot that I was looking at so closing out as mentioned. Great job @jaimiebutton

**Comment by hannavovk** [comment]
Concluded in conjunction with #178 that it was the right spot that I was looking at so closing out as mentioned. Great job @jaimiebutton
