### ISSUE TITLE
Identify target external groups to conduct research with 

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#180]
Who do we want to talk to in our external research?

Acceptance Criteria:
- [x] Identify broad categories of external users (eg. operators, verifiers, etc.)
- [x] Split up broad categories into different types of users
- [x] Share with Team Moose for feedback
- [x] Check out the Engagement team's bilateral meeting notes + sentiment analysis for groups we missed
- [x] Ideate which of the groups would be ideal candidates for registration + reporting research

Goal of this ticket:
- Have an understanding of who specifically we want to talk to in our research
- Be able to share this with the Policy team to find overlap in our engagement efforts

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/180?planning-poker) with Zenhub @nanyangpro

**Comment by hannavovk** [comment]
Thanks @jaimiebutton!
