### ISSUE TITLE
Plan for Participatory exploration & design session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#182]
Acceptance Criteria:
- [x] Establish goals for session
- [x] Ideate what outputs we would like by the end of the session
- [x] Narrow down scope of which topics to focus on in the session
- [x] Create rough structure
- [x] Pass rough structure to team moose for feedback
- [x] Iterate on feedback
- [x] Write agenda for session
- [x] Schedule session

Goals of ticket:
- Get ready for the session!

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/182?planning-poker) with Zenhub @nanyangpro

**Comment by nanyangpro** [comment]
Hi @jaimiebutton - Would you please assign me to this ticket? I lost the ability to assign myself or make edits to all the Moose ticket in the cas-review repo somehow. :(
![image.png](https://images.zenhubusercontent.com/5e3b4990c0f4cb9e2c9b1b1e/62cd4a00-270e-44a9-b53a-bbf3657a1aa5)

**Comment by jaimiebutton** [comment]
@nanyangpro Yes assigned us!

**Comment by nanyangpro** [comment]
Amazing, thanks @jaimiebutton!
I updated tomorrow's Moose Working Meeting invite for us to get started. Feel free to add things missing there.

**Comment by nanyangpro** [comment]
Hi @jaimiebutton - The team had the planning discussion on Tue, Jul 4. Here's the rough [session structure and highlights](https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764558334264717&cot=14) for you to review/refine. Thanks!

**Comment by nanyangpro** [comment]
Closing this ticket as the planning is done to unblock #166.
