### ISSUE TITLE
Create registration lo-fi wireframe

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#187]
Taking what we worked on during the co-design wireframe session with the IRC Registration team, let's compile what was created and brainstorm our own refined wireframes.

Acceptance Criteria:
- [x] Compile all wireframes created during the co-design session on Miro
- [x] Pull out parts from each that would be helpful in refined wireframes
- [x] Create our own refined wireframes using the wireframes compiled
- [x] Pass to Team Moose for feedback and iterate on feedback, if needed
- [x] Pass to the IRC Registration team for feedback and iterate on feedback, if needed

Goal of this ticket:
- Take the rough work done during the co-design session and make sense of it 
- Create 3 refined wireframes of different design options

**Comment by nanyangpro** [comment]
Discussed with @hannavovk on Fri, Jul 14:
- This can be done in parallel with #176
- This ticket depends on how much alignment we can get from the session with IRC, i.e. blocked by #174. We may need to revisit and refine this ticket based on that. A second session with IRC may need to be scheduled before this ticket.

**Comment by jaimiebutton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/187?planning-poker) with Zenhub @andrea-williams @nanyangpro

**Comment by nanyangpro** [comment]
Hi @hannavovk & @patriciarussellCAS - This ticket is ready for you to review and can be closed with the following interactive prototypes created and demoed
- [Workflow 1 - Request access to org as the first user (Prime Gertrude)](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/Registration-app?page-id=4%3A2&type=design&node-id=50-3570&viewport=365%2C284%2C0.29&t=LGmIKJ906VKB2FH9-1&scaling=scale-down&starting-point-node-id=50%3A3570&show-proto-sidebar=1&mode=design)
- [Workflow 2 - Request access to org as a subsequent user (Regular Gertrude)](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/Registration-app?page-id=4%3A2&type=design&node-id=50-3694&viewport=365%2C284%2C0.29&t=LGmIKJ906VKB2FH9-1&scaling=scale-down&starting-point-node-id=50%3A3694&show-proto-sidebar=1&mode=design)
- [Key Screen Walkthrough - Internal app + External app](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/Registration-app?page-id=4%3A2&type=design&node-id=5-6&viewport=365%2C284%2C0.29&t=LGmIKJ906VKB2FH9-1&scaling=scale-down&starting-point-node-id=5%3A6&show-proto-sidebar=1&mode=design)

and follow-up tickets created
- #227
- #228

**Comment by hannavovk** [comment]
Very impressive and quick work on this @nanyangpro! So helpful!
