### ISSUE TITLE
Plan & Host Overall Digital Services Design Workshop

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-review#189]
#### Describe the task

This Overall Digital System Design Workshop will take place after and could be informed by the Q2 Roadmap Release Planning session on Jul 12, 2023. The [Hypothetical Dependency/Process Map for Users](https://miro.com/app/board/uXjVP1NVDKE=/?moveToWidget=3458764557870516575&cot=14) could be used as a reference.

**Preliminary Session Goals (could be adjusted based on team input):**
- Kick-off the conversation for achieving the Q2 goal of the overall digital services design
- Propose, discuss and agree on
    - How services are grouped/separated from each other?
    - On which web app / platform / tool will what part of the process take place?
    - Naming conventions for different services/components (web apps, platforms, tools etc.)

**Session Scope:**
- All the services required in support of the carbon pricing transition on a high-level
- For the future, we'll keep zooming into details of each service/topic one by one, as we've been doing for Registration

#### Acceptance Criteria

- [x] Schedule meeting
- [x] Gather team input for goals/deliverables
- [x] Confirm PO visions (HV & PB) before PB leaves
- [x] Structure session agenda and update meeting invite
- [x] Build out Miro frames (context, example) to support session
- [ ] Create in-person materials (if required)
- [x] Host the workshop
- [x] Identify next steps

**Comment by nanyangpro** [comment]
Hi @hannavovk & @pbastia - This ticket is created to address that separate High-Level System Design Workshop as discussed during the Moose Working Meeting.

To make sure your expectation/vision is properly captured. Please take a look and refine as you fit. Thank you!

**Comment by Dianadec** [comment]
Try to schedule by end of July to include Pierre and Dylan.

**Comment by nanyangpro** [comment]
Hi @hannavovk (cc: @pbastia, @Dianadec) - Thanks for the context and clarifications! I've refined this ticket based on our discussion, feel free to review and refine it further!

@Dianadec - Could you please help me put a hold for 3 hours (might be shortened based on the prep for the session) in people's calendars, Hanna suggested in the week following the next.

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/189?planning-poker) with Zenhub @andrea-williams @dleard @jaimiebutton @nanyangpro @NicoleGovvy

**Comment by nanyangpro** [comment]
Hi @hannavovk & @patriciarussellCAS - This ticket is ready for you to review and can be closed with the outputs summarized below:

### Tentative design of system structure
- According to @dleard and @andrea-williams, the proposals are very much aligned from the developers' perspectives.

### Unblock coding
- According to @dleard and @andrea-williams, current blockers are unknowns and pending decisions from IRC.
- Once the approach is chosen, development of Registration could be unblocked fairly quickly.

### Naming conventions & Repo (for DST internal communication)
- **Registration app** (cas-registration)
- **Reporting app** (cas-reporting)
- **Calculation module** (towards emissions, potential)
- **Compliance app FE** (cas-compliance-fe)
- **Compliance app BE** (cas-compliance-be)
- **Data Warehouse** (cas-data-warehouse)

### Next steps
- @jaimiebutton will create a ticket to address: an artifact that splits out the major 'apps/components' and their: proposed MVP features and proposed complete features.
- @dleard will create a ticket to address: the initial ERD diagram for Registration.

Thanks @NicoleGovvy & @Dianadec for your great help towards planning and facilitation!

**Comment by hannavovk** [comment]
Awesome session, thanks all! And thanks @nanyangpro for planning and leading this!
