### ISSUE TITLE
Map out potential auth options

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-review#191]
We need to come up with some options around authentication and authorization for the registration process. Each option should have the risks and benefits clearly defined. Suggest using a miro board to capture the different options in one place.

Some things to consider:
- Data prepopulation from CIIP
- Integration with orgbook
- Business BCeID and potential for vendor lock-in
- Delegation of authority at registration time
- User registration data for use in OBPS

**Comment by andrea-williams** [comment]
@dleard are you expecting decisions re: which option to use to come out of this ticket, or would that be a follow-up ticket (presumably after a team discussion)?

**Comment by dleard** [comment]
What I had in mind here is to come up with a few options to present to POs. For example, does it make auth easier if we do no pre-population? In coming up with options I'm sure we'll have a couple that we would recommend over others, but ultimately I think we should have several options outlined with the risks and benefits associated with each.

**Comment by Dianadec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/191?planning-poker) with Zenhub @andrea-williams @dleard @JoshLarouche
