### ISSUE TITLE
Schedule wireframe co-design session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#192]
Scheduling time to have a co-design session with the IRC Registration team to generate some rough wireframes.

Acceptance Criteria:
- [x] Find time over the next sprint in people's calendars (ideally 1.5hr - 2 hrs)
- [x] Book hold in calendars
- [x] Include rough agenda

Goals of this ticket:
- Get a session booked before calendars fill up!

**Comment by jaimiebutton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/192?planning-poker) with Zenhub @andrea-williams @nanyangpro

**Comment by nanyangpro** [comment]
Hi Hanna - This ticket is ready for you to review and can be closed with:

- The Co-Wireframing session scheduled on Wed, Aug 16 afternoon
- Detailed agenda included in the meeting invite
