### ISSUE TITLE
Plan for wireframe co-design session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#193]
Let's make sure we're ready to go for the wireframe co-design session!

Acceptance Criteria:
- [x] Brainstorm high-level goals of session
- [x] Brainstorm ideal outputs/deliverables by end of session
- [x] Get feedback from Team Moose + iterate on feedback if needed
- [x] Plan out rough session agenda
- [x] Build out Miro boards to support session
- [ ] Create in-person materials, if needed

Goal of this ticket:
- Be clear on the scope of the session
- Ensure we get what we need to get out of it

**Comment by nanyangpro** [comment]
Hi @hannavovk - This ticket is ready for you to review and can be closed with:

- The [co-wireframing session](https://miro.com/app/board/uXjVMvHaL60=/?moveToWidget=3458764561324594028&cot=14) hosted on Wed, Aug 16.
- The [reflections and questions for PO/SM/rest of team](https://miro.com/app/board/uXjVMvHaL60=/?moveToWidget=3458764561792592894&cot=14) documented post the session.

**Comment by hannavovk** [comment]
Thanks @nanyangpro! Awesome job planning and facilitating the session.
