### ISSUE TITLE
Hold wireframe co-design session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#194]
Ready to wireframe? Let's do it!

Acceptance Criteria:
- [x] Update the agenda beforehand, if needed
- [x] Hold hybrid session
- [x] Document next steps

Goals of this ticket:
- Have a collaborative wireframing session with the IRC Registration team to generate some ideas for rough wireframes

**Comment by nanyangpro** [comment]
Closed. Please see details in #193.
