### ISSUE TITLE
Plan and hold user story mapping session for Registration

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#197]
LOGISTICS
- [x] Schedule the session and book a room
- [x] Setup user story template
- [x] Setup agenda and update the meeting invite
- [x] Determine in-person/online/hybrid
- [x] If in-person, gather facilitation kit: sharpies, sticky notes, brown paper, etc.

CONTENT PREP:
- [x] Confirm Personas with UX and business area
- [x] Create visuals of persona details - see BC Parks Example: https://bcgov.sharepoint.com/:f:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/BC%20Parks?csf=1&web=1&e=czISSN
- [x] Create a Definitions board of common terms, acronyms and terminology defined
- [ ] Create powerpoint to support the workshop - See BC Parks example: https://bcgov.sharepoint.com/:p:/t/031072/ERyPAWBbPYZOkEdAmzGXZAYBsVGWnO26G_FNkaTnn7qf8Q?e=5NYVgG
- [x] Setup story mapping template - timeline

**Comment by Dianadec** [comment]
Booked meeting room 4003 for potential in-person attendance. However, the workshop will be optimized for online/hybrid participation using miro board.

**Comment by Dianadec** [comment]
Next steps posted in scrum team and visual created in the miro board.

**Comment by hannavovk** [comment]
Thanks @Dianadec and team! It was a great session.
