### ISSUE TITLE
Plan personas/user groups for story mapping

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-review#212]
#### Describe the task

We will need user groups/personas for the story mapping workshop.

#### Acceptance Criteria

- [x] Determine scope
- [x] Fill in personas/user groups
- [x] PO Review

Update: confirmed user role outline is most suited for story mapping scope with Diana. Will use work completed already by Nan to create hypothetical user roles and tasks.

Roles for registration:
1. Industry super user
2. Industry user
3. CAS staff member

https://miro.com/app/board/uXjVMxrlLbM=/?moveToWidget=3458764560824057997&cot=14

#### Additional context

Nan has created some starting user roles:
<img width="89" alt="image" src="https://github.com/bcgov/cas-review/assets/128426411/9520b9d4-4307-4a99-8b3f-e644bcc0aba8">

**Comment by NicoleGovvy** [comment]
@hannavovk Hi Hanna, if you have some time this morning - I've got 3 profiles for our story mapping workshop (focused on system roles for registration) that it would be great to get your eye one - if there's any comments/updates it would be great. https://miro.com/app/board/uXjVMxrlLbM=/?moveToWidget=3458764560824057997&cot=14

**Comment by hannavovk** [comment]
@NicoleGovvy Thanks Nicole! Looks good to me. I had one comment that's more just a clarification that may or may not need to be incorporated. Up to you.

**Comment by NicoleGovvy** [comment]
@hannavovk thanks! I've added that extra bullet.
