### ISSUE TITLE
Task: Plan experimentation weeks/sprint

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-review#213]
#### Describe the task

This card to plan the experimentation sprint or 'team Hackathon'

#### Acceptance Criteria

- [x] create Miro board explaining purpose, collect initial ideas for potential projects
- [x] meet w/ POs & SMs to discuss duration & timing; collect further project ideas from POs
- [x] meet w/ entire Scrum Team to introduce idea, Q&A

#### Additional context

- Miro board: https://miro.com/app/board/uXjVMy_xsys=/

**Comment by pbastia** [comment]
@andrea-williams I'm assigning you to this, to bring it up during the appropriate refinement session

**Comment by pbastia** [comment]
cc @hannavovk @Dianadec @rdromey

**Comment by andrea-williams** [comment]
Miro board for planning this: https://miro.com/app/board/uXjVMy_xsys=/
