### ISSUE TITLE
Connected Services Map

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#215]
Following the Overall Design Workshop, we identified the need for a visual artifact that maps out our proposed 'services' and their core features.

Acceptance Criteria:
- [x] Compile existing 'overall services' maps
- [x] Create rough map of 'apps'/'modules'
- [x] Pass to team for feedback
- [x] Iterate on feedback if needed
- [x] Pass to PO for feedback

Goal of this ticket:
- Create an artifact that can be used & iterated upon both internally and in conversation with the program area

**Comment by hannavovk** [comment]
Thanks @jaimiebutton - this has been very helpful! I've been using it a lot already as a visual aide!
As mentioned, I had some comments and made some tweaks - copied my version as a separate frame on the board for team use or reference [https://miro.com/app/board/uXjVPo-utew=/?moveToWidget=3458764562327608566&cot=14](url)
