### ISSUE TITLE
Registration service blueprint

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#217]
A service blueprint gives a complete picture of how the service and related experience is delivered, end to end, front to back and across channels. As we get closer to nailing down our registration process + requirements, it would be helpful to synthesize our learnings into a service blueprint that includes external user, internal staff, and system interactions. 

Acceptance Criteria:
- [x] Find some helpful existing blueprint templates
- [x] Determine the start and ending stages of the blueprint
- [x] Determine the actors to be depicted in the blueprint 
- [x] Gather previous maps made, including from this month's IRC Registration workshop and the board in the Nan's Notes miro board
- [x] Create rough service blueprint
- [x] Pass to scrum team for feedback
- [x] Iterate on feedback, if needed

Goal of this ticket:
- Create a common resource we can use for user story mapping & future registration work
- Communicate the registration process in plain language to IRC

**Comment by jaimiebutton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/217?planning-poker) with Zenhub @nanyangpro @NicoleGovvy

**Comment by NicoleGovvy** [comment]
NN template - https://www.nngroup.com/articles/service-blueprints-definition/
