### ISSUE TITLE
Touch base w/IRC on an engagement plan

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#221]
We met with IRC a few sprints ago to discuss engagement opportunities, where at the time both teams were still unsure of their plans. Now that we have a better idea of our engagement plan, let's meet to see if there are any opportunities for alignment! 

Acceptance Criteria:
- [x] Schedule team with us and IRC/Engagement team
- [x] Write meeting agenda ahead of time
- [x] Meet with team and discuss opportunities for alignment
- [x] Document opportunities

Goal of this ticket:
- Identify if our plans have any overlap before we go ahead on our own

**Comment by jaimiebutton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/221?planning-poker) with Zenhub @nanyangpro @NicoleGovvy

**Comment by Dianadec** [comment]
Assigning myself to help get this setup but feel free to add your name as the researchers/designers taking on the content part :)

**Comment by hannavovk** [comment]
Awesome! Thanks @jaimiebutton
