### ISSUE TITLE
Reach out to LCFS Digital Team

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#224]
Let's connect with the Low Carbon Fuel Standards (LCFS) digital team to understand where overlaps lie in our work with credit trading.

Acceptance Criteria:
- [x] Reach out to Justin (Acting Director for LCFS)
- [x] Set up session

Goal of this ticket:
- Understand where we can lean on LCFS' existing research/UX work

**Comment by jaimiebutton** [comment]
In a fun turn of events, TFRS and LCFS are the same system.

**Comment by hannavovk** [comment]
Thanks for setting this up @jaimiebutton!
