### ISSUE TITLE
Reach out to TFRS Team

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#225]
Let's connect with the Transportation Fuels Reporting System (TFRS) team to understand where overlaps lie in our work, both with data reporting + earned credit trading.

Acceptance Criteria:
- [x] Reach out to Al from TFTS
- [x] Set up session

Goal of this ticket:
- Understand where we can lean on TFRS' existing research/UX work

**Comment by hannavovk** [comment]
Very useful session. Thanks @jaimiebutton
