### ISSUE TITLE
Confirm Data IRC & FIN Needs for Registration and Carbon Tax Exemption

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#229]
What data does IRC & FIN need from our registration app? Let's find out!

Acceptance Criteria:
- [ ] Review document sent over by Jose A.
- [ ] Get IRC's feedback on Jose's proposed data fields
- [ ] Get an idea of what data Finance needs for carbon tax exemption
- [ ] Create finalized list of data needed for registration
- [ ] Create finalized list of data FIN need for carbon tax exemption

Goal of ticket:
- Nail down what datafields will be needed for registration

**Comment by nanyangpro** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/229?planning-poker) with Zenhub @nanyangpro @jaimiebutton @NicoleGovvy

**Comment by nanyangpro** [comment]
Closed as addressed in bcgov/cas-registration#33.
