### ISSUE TITLE
Build out frame for Roles & Responsibilities session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#30]
One of the action items from the whiteboarding session with M.S. was to hold a session to clarify roles & responsibilities.

Acceptance Criteria:
- [x] Identify goals of session
- [x] Create Miro space for session
- [x] Build out structure of workshop
- [x] Pass to surge team for feedback

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton - is there anything I can take a look at for this ticket?
