### ISSUE TITLE
Review Maral's PPT

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#39]
Before the holidays, Maral created a powerpoint document to track progress.

Acceptance Criteria:
- [x] Review PPT
- [x] Ask clarifying questions, if needed
- [x] Document opportunities for communicating information to the bigger group
- [x] Redesign 'next, now, later' view
- [x] Pass to transition team for feedback

**Comment by jaimiebutton** [comment]
Comments from Maral:

Q: Are you looking for some visual re-jigging to be able to present this to Adria or visual re-jigging to make this an artifact that's helpful for the CPR team to use? (which 'stakeholder group' is your most pressing priority?)
A: I think the priority is making this an artefact for the CPR team and the rest of the branch to better understand timelines and priorities.

Q: Is there anything specifically that I can do to help for the PPT, or just take a look & do things?
J: I imagine it’s evident, but I think visualizing timelines is the thing I’m struggling with the most. What suggestions do you have, if any, around how to communicate things happening over time to a bigger group without overloading graphics with too many things (but also without minimizing work to be done). I’m struggling with finding that balance, I suppose, so any suggestions/help you can offer I’m here for!

Q: What's your timeline for this?
A: Would earlyish January work for you?

Also, is there anything else besides the PPT that I can help take off your plate?

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - I add a checklist item to capture redesign the ppt to be more accessible/digestible. After speaking with Maral, is it possible to have this work completed by the end of this week?

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - anything I can take a look at for this ticket?
