### ISSUE TITLE
Help brainstorm 'branch inception'

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#40]
Acceptance Criteria:
- [x] Create facilitation plan for branch inception brainstorming on Jan. 30
- [x] Hold Jan. 30 session w/MS
- [x] Transcribe whiteboard to Miro
- [x] Document next steps

**Comment by LindsayMacfarlane** [comment]
Thank you for all your support with the Governance Team @jaimiebutton - I know they very much appreciate it.
