### ISSUE TITLE
Plan for Agile x Policy session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#44]
On Jan. 16, the team will be bringing together folks from a bunch of different areas to talk about their experience combining policy with an agile framework. Let's do some work to prepare for this conversation :)

Acceptance Criteria:
- [x] Define goals for session
- [x] Define format of session
- [x] Build out supporting materials/Miro space, if needed
- [x] Share with project team for feedback
- [x] Iterate on feedback, if needed

**Comment by Dianadec** [comment]
@jaimiebutton I'd be happy to help with this if/as needed :) Thanks for making a ticket for it!

**Comment by LindsayMacfarlane** [comment]
Thank you so much for pulling this together @jaimiebutton ! I very much look forward to our session later today :)
