### ISSUE TITLE
Set up chat with MS & LM

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#45]
To properly scope out work & priorities for the next few weeks, let's meet as a team to discuss next steps.

Acceptance Criteria:
- [x] Set up chat with MS & LM for week of Jan. 9
- [x] Identify goals of chat

**Comment by jaimiebutton** [comment]
Chat took place with MS on Jan 12 :)

**Comment by LindsayMacfarlane** [comment]
Thanks @jaimiebutton - was I there for that chat?

**Comment by jaimiebutton** [comment]
Hello! No, it ended up just being with MS but happy to have another alignment session :)
