### ISSUE TITLE
What goes into an engagement plan?

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#46]
An engagement plan is coming! But - what the heck goes into an engagement plan? Before we start building one out, let's identify goals to understand the scope and be able to plan accordingly.

Acceptance Criteria:
- [x] Research & pull together parts of a research plan from online sources
- [x] Create draft skeleton structure
- [x] Pass skeleton structure to Surge Team & Project Team for feedback
- [x] Iterate based on feedback if needed

**Comment by jaimiebutton** [comment]
Hey @LindsayMacfarlane , how does this ticket sound to you?

**Comment by LindsayMacfarlane** [comment]
Looks good @jaimiebutton. One thing that may be worth including is how and when service design/ux research fits into the plan.

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - please loop in @suhafa

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton! I'm excited for the next steps in all the service design work.
