### ISSUE TITLE
Initial chat with Avril on engagement

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#5]
As Avril will be planning out engagement, let's meet for an initial discussion on how we can align.

Acceptance Criteria
- [x] Schedule time with Avril
- [x] Meet to discuss engagement
- [x] Bring outcomes back to team

**Comment by LindsayMacfarlane** [comment]
Let's see how you can support more on this. I showed Hanna the planning work that went into the PR project. Perhaps that could be valuable. We should also set up a meeting with Jess K as she's been tasked to coordinate/lead on engagement work. Can you set that up for us?

**Comment by jaimiebutton** [comment]
@LindsayMacfarlane Absolutely! I'll add a ticket to capture that work.
