### ISSUE TITLE
Review and inventory reusable components

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-review#50]
#### Description
Review existing components and features to determine what can be packaged as a reusable component.

Different categories can be:

- type (code, devops, ...)
- technology (language, framework)
- where that refactored, reusable package would live
- the amount of effort involved:
       - to publish a reasonably well documented package, with automated tests, release, etc.
       - to refactor our various apps that would make use of it

#### Checklist
- [x] setup a get-together to look through repos and brainstorm / categorise what can be reused
- [x] create a miro board to record and classify findings
- [x] prioritize items to refactor
- [ ] review and cleanup the Template App [EPIC](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-template-app/6)
- [ ] create follow up tickets (as required)

#### Notes
- consider documenting in CAS-Home
- this also relates to system architecture review

**Comment by LindsayMacfarlane** [comment]
@pbastia @dleard - would be grateful for your input on this ticket. From a developers perspective what is needed to do an inventory and plan next steps?

**Comment by pbastia** [comment]
@LindsayMacfarlane I think we need to spend some time with a few developers, to look through the various code bases that we have, and classify, for each opportunity:
- type (code, devops, ...)
- technology (language, framework)
- where that refactored, reusable package would live
- the amount of effort involved:
    - to publish a reasonably well documented package, with automated tests, release, etc.
    - to refactor our various apps that would make use of it

**Comment by LindsayMacfarlane** [comment]
Backlog Refinement (Feb 22, 2023): DL wanted to review capacity before pulling ticket into this sprint.

**Comment by pbastia** [comment]
@gurjmatharu following your comment, I put a card about the file upload / download UI from CCBC on the board

**Comment by dleard** [comment]
I've added some comments to the board and added a couple stickies (CrunchyDB monitoring chart, RLS/timestamp database helper functions)
