### ISSUE TITLE
Analyze program discovery strategy w/LM

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#53]
Using the Miro map from the Data Warehousing Strategy, how can we strategize our coordination/discovery of program areas?

Acceptance Criteria: 
- [x] Take stock of which program areas are relevant to discovery
- [x] Prioritize program areas on matrix of need & urgency
- [x] Create a list of next steps

Note:
- If needed, create rough prioritized list of program areas based on matrix
- If needed, create discovery roadmap using prioritized list

**Comment by LindsayMacfarlane** [comment]
Thanks for this session @jaimiebutton - it was really helpful to start thinking about next steps for service design and kick starting conversations with the various units to better understand digital service needs. I'm excited!
