### ISSUE TITLE
Plan Open Questions session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#54]
We have many unknown unknowns. Let's try to turn some of them into known unknowns! By consolidating our open questions, we can pull out common themes to go into an engagement plan & identify gaps in our knowledge for future spikes/research.

Acceptance Criteria:
- [x] Schedule session with DST
- [x] Create Miro space to hold questions
- [x] Build out session goals
- [x] Create session outline/frame
- [x] Bring in Qs from team brainstorm session
- [x] Build out Miro session

**Comment by LindsayMacfarlane** [comment]
Thanks @jaimiebutton!
