### ISSUE TITLE
Coffee chat w/Patricia

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#55]
Acceptance criteria:
- [x] Reach out to Patricia
- [x] Schedule coffee chat
- [x] Hold coffee chat
- [x] Report back to scrum team on any action items, if applicable

**Comment by jaimiebutton** [comment]
Action items - Loop Patricia into discovery sessions, schedule another conversation to talk about creating problem statements with program areas

**Comment by LindsayMacfarlane** [comment]
Looking forward to hearing how this went. Thank you @jaimiebutton
