### ISSUE TITLE
How do we want to capture learnings from discovery w/program areas?

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#58]
We'll be learning a lot of things, very soon! Let's strategize how we'll capture these learnings ahead of time.

Acceptance Criteria:
- [x] Ideate where we can hold information
- [x] Ideate how we can capture information during interviews
- [x] Poll Scrum team for preference
- [x] Brainstorm what goes into an interview note-taking template
- [x] Create templates based on poll results

**Comment by nanyangpro** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/58?planning-poker) with Zenhub @jaimiebutton

**Comment by pbastia** [comment]
@jaimiebutton where are the templates stored?

**Comment by jaimiebutton** [comment]
@pbastia they're in Scrum Tea -> Files -> CPR -> Interview Notes & Recordings

**Comment by pbastia** [comment]
I can see it! Thanks @jaimiebutton, great work!
