### ISSUE TITLE
Hold Open Questions session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#62]
Following ticket #54, this ticket captures holding the CPR Open Questions session with the scrum team.

Acceptance Criteria:
- [x] Hold session
- [x] Compile open questions
- [x] Pass questions & categories back to scrum team, if applicable

**Comment by jaimiebutton** [comment]
Note: During the session it was identified that it is too early in the process to track more questions or be able to plan for engagement - will need to revisit this at a later date!

**Comment by LindsayMacfarlane** [comment]
Thanks @jaimiebutton! Agree we will need to circle back to this at a later date, but I'm happy that we've started to address documentation.
