### ISSUE TITLE
Build out Roles & Responsibilities session

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#63]
Following ticket #30, this ticket captures building out a Miro workshop to facilitate the Surge team's roles & responsibilities session.

Acceptance Criteria:
- [x] Schedule session with Surge Team members
- [x] Create individual frames for each session section
- [x] Fill out each section
- [x] Pass to JK for feedback
- [x] Iterate on feedback if possible

**Comment by LindsayMacfarlane** [comment]
Thanks @jaimiebutton!
