### ISSUE TITLE
Discuss governance team scaffolding w/Avril

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#65]
After discussing with JK, Avril has some capacity for building out scaffolding for the governance team. Scaffolding can include how we'll interact on Teams, structuring our bi-weekly check-ins, and how we'll share progress with each other.

First, let's meet to discuss what can be done collaboratively. 

Acceptance Criteria:
- [ ] Schedule time with Avril
- [ ] Brainstorm ways to work together to build out team scaffolding
- [ ] Document opportunities & next steps
- [ ] Share opportunities & next steps with surge team for feedback
- [ ] Iterate on feedback, if needed

**Comment by Dianadec** [comment]
@jaimiebutton if it is helpful to see another Agile framework other than scrum to support some of these conversations, this Mural board shows the diff between Scrum and Kanban and shows how Kanban can be explored by a team. It was created by a fellow scrum master :). https://app.mural.co/t/embark9052/m/embark9052/1638924696564/6232584194b7a6d8a18f38c10940b64a751f2bf8?sender=8d1554fa-53a3-4837-9777-2632c9dd97cf

**Comment by LindsayMacfarlane** [comment]
CPR Refinement (March 2): Based on feedback, pulling this ticket into icebox as it is no longer a priority. In addition, Jaimie is slightly offboarding from the Governance Team. Governance will also be addressed through the upcoming Branch Inception. Let's review this ticket in a month > if no longer required we can close.

**Comment by jaimiebutton** [comment]
Closing this ticket as it's no longer relevant
