### ISSUE TITLE
Offsets: Prod API exploration

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-review#70]
#### Checklist:
- [x] get Prod API documentation from BCCR
- [x] download all the data or a subset of it
- [x] put it in a metabase instance

#### Notes:

**Comment by LindsayMacfarlane** [comment]
Note: @dleard and myself met with IHS Markit to discuss getting access to data not available through the public API. Within the next month, they will provide us a list/schema of fields available, including potential unique identifiers.

**Comment by pbastia** [comment]
Investigate feasibility of automated pulling of private data
