### ISSUE TITLE
Schedule Discovery on Metabase (DST)

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#72]
#### Task:
Conduct 'discovery light' on current metabase use and accessibility to better understand user needs. Results will help inform decisions on whether Metabase is still the appropriate tool to support the branch or if an alternative needs to be aquired.

#### Checklist:
- [x] Schedule conversations with identified participants

(Include 1 developer in invite)

**Comment by LindsayMacfarlane** [comment]
Thank you for setting this up @jaimiebutton
