### ISSUE TITLE
More Offsets Exploration

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-review#73]
#### Checklist:
- [x] put it in a metabase instance
- [x] review what we've got so for with IRC (CF, RT, KC) & validate information
- [x] start looking at common keys with swrs data

**Comment by LindsayMacfarlane** [comment]
FYI @dleard - if you are bringing in offset data into metabase, take a look at this existing ticket.

**Comment by pbastia** [comment]
This was just made available on our -test instance of metabase. It's currently not available for all members of the organisation, but can be enabled on a case by case basis.

**Comment by LindsayMacfarlane** [comment]
Reviewed initial public API data with RT from program area.
