### ISSUE TITLE
Create structure for Internal Discovery Plan

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#78]
Our Internal Discovery plan will help us plan out discovery goals, activities & scope. 

Acceptance Criteria:
- [x] Create space in DST Thinking Miro for discovery planning
- [x] Create frame for Overview
- [x] Create frame for Goals & Questions
- [x] Create frame for Logistics
- [x] Create frame for Analysis & Presentation
- [x] Bring in research plan from Public Reporting

**Comment by pbastia** [comment]
Thank you @jaimiebutton ! The structure is in Miro
