### ISSUE TITLE
Analyze discovery lite feedback

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#82]
A time of learning many things! Let's compile findings and find insights.

Acceptance Criteria:
- [x] Bring content from Miro frames together into one frame
- [x] Translate comments into stickies for analysis
- [x] Document any patterns in responses
- [x] Generate a list of potential focus areas from discovery feedback
- [x] Prioritize focus areas generated
- [x] Share focus areas with PO & scrum team 
- [x] Nan to review outcome asynchronously
- [x] Jaimie & Nan come together to discuss

**Comment by pbastia** [comment]
Thank you @nanyangpro and @jaimiebutton ! We've reviewed the areas of focus together last week
