### ISSUE TITLE
Review the SWRS report

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#86]
The SWRS report will be a helpful document for our review work. Let's go back through that document to pull out things that can be used in our documentation for execs.

Acceptance Criteria:
- [x] Skim through the SWRS report
- [x] Pull out negatives identified
- [x] Pull out risks identified
- [x] Pull out alternatives identified, if any
- [x] Pull out any other information that may be relevant
- [x] Store this information in a Miro frame

Goal of this ticket:
- Utilize the work done for the report to reduce work duplication in our review

**Comment by pbastia** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/86?planning-poker) with Zenhub @dleard

**Comment by pbastia** [comment]
This is done! Results are in the DST CPR thinking miro board
