### ISSUE TITLE
Go back through original CPR journey map

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#89]
Lots of good work was done over the last few months that may inform our understanding of stakeholders' work to be done. Let's go back through the original CPR journey map to glean any insights that may be there.

Acceptance Criteria:
- [x] Review journey maps in Miro
- [x] Take inventory of what maps exist
- [x] Make note of any insights that can be added to discovery lite findings that we didn't uncover in our own work
- [x] Bring insights over to DST's CPR Thinking Miro

Goal of ticket:
- Make sure we're not losing any work that's been done in the past
- Be able to inform our own internal/external user journey maps when we make them

**Comment by LindsayMacfarlane** [comment]
Hi @jaimiebutton > can you please refine this ticket if you'd like to pull it into next sprint.

**Comment by LindsayMacfarlane** [comment]
Ignore the above @jaimiebutton - I'm reviewing the wrong column :)

**Comment by nanyangpro** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/89?planning-poker) with Zenhub @jaimiebutton

**Comment by pbastia** [comment]
Thank you @jaimiebutton !
