### ISSUE TITLE
Data Warehousing Strategy_Preliminary Research 

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-review#91]
#### Describe the task

We know as a team, we would like a data warehousing strategy to better help our development work moving forward and to ensure our data is accessible and interoperable. 

#### Acceptance Criteria

- [x] What already exists in BC Government around data warehousing strategies?
- [x] Reach out to other teams
- [x] Reach out to data experts (data architects)
- [x] create other tickets (as needed) based on research insights

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by pbastia** [comment]
Avenues to explore:
- access control, granularity (is metabase enough?)
- admin functionality
- DataBC scopes and Public scopes
- examples of cross-db queries, user stories

**Comment by pbastia** [comment]
Reach out both at PO level and Dev level

**Comment by dleard** [comment]
A new epic and tickets have been created for the next steps on data warehousing. Closing this card
