### ISSUE TITLE
Plan for Problem Statement Workshops

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#97]
Helping each unit create a problem statement to represent their work to be done will help us understand each team's core digital system needs, as well as will helping each team gain visibility into others at branch inceptions. 

To start, let's brainstorm how we can facilitate each team's problem statement(s).

Acceptance Criteria:
- [x] Identify goals of problem statements
- [x] Identify outcomes of problem statements
- [x] Create generic problem statement template
- [x] Create rough Miro frame for workshop
- [x] Get feedback from PR
- [x] Iterate on feedback, if any
- [x] Build out Miro workshop

**Comment by LindsayMacfarlane** [comment]
Looks good @jaimiebutton! My main question: do teams get to have multiple problem statements or are we hoping each team presents one? If multiple teams identify similar problem statements, do we then hope to theme those and pick our top problem statements for the app?
