### ISSUE TITLE
Schedule Problem Statement Workshops

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#98]
Helping each unit create a problem statement to represent their work to be done will help us understand each team's core digital system needs, as well as will helping each team gain visibility into others at branch inceptions. 

This ticket captures the scheduling of problem statement sessions.

Acceptance Criteria:
- [x] Create meeting agenda
- [x] Schedule session with R&A
- [x] Schedule session with C&E
- [x] Schedule session with EMU
- [x] Schedule session with ICU

**Comment by LindsayMacfarlane** [comment]
Thank you @jaimiebutton (and to Patricia)!
