### ISSUE TITLE
Hold Problem Statement Workshops

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#99]
Helping each unit create a problem statement to represent their work to be done will help us understand each team's core digital system needs, as well as will helping each team gain visibility into others at branch inceptions. 

Acceptance Criteria:
- [x] Hold session with R&A and document findings
- [x] Hold session with C&E and document findings
- [x] Hold session with EMU and document findings
- [x] Hold session with ICU and document findings

**Comment by pbastia** [comment]
Workshops were held indeed. Thank you @jaimiebutton !
